// src/pages/Register.tsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { register } from '@/lib/api';
import Button from '@/components/ui/Button';
import Input from '@/components/ui/Input';
import Navbar from '@/components/Navbar';
import Toast from '@/components/ui/Toast';
import { pageTransition } from '@/lib/animations';

export default function Register() {
  const navigate = useNavigate();
  const [form, setForm] = useState({
    email: '', password: '', nickname: '', gender: 1, birth_date: '', city: '', bio: '', tags: ''
  });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [toast, setToast] = useState({ visible: false, message: '', variant: 'success' as 'success' | 'error' | 'info' });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      const data = await register({
        ...form,
        gender: Number(form.gender),
        tags: form.tags ? JSON.stringify(form.tags.split(',').map((t: string) => t.trim())) : '[]',
      });
      localStorage.setItem('token', data.access_token);
      localStorage.setItem('user', JSON.stringify(data.user));
      setToast({ visible: true, message: '注册成功', variant: 'success' });
      setTimeout(() => navigate('/discover'), 800);
    } catch (err: any) {
      setError(err.message);
      setToast({ visible: true, message: err.message, variant: 'error' });
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <Navbar />
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} transition={{ duration: 0.35, ease: [0, 0, 0.2, 1] }} className="max-w-md mx-auto mt-10 px-4 pb-20">
        <h1 className="text-2xl font-bold text-center mb-6 text-gray-900 dark:text-gray-100">创建账号</h1>
        <form onSubmit={handleSubmit} className="bg-white dark:bg-gray-900 rounded-2xl shadow-md p-6 space-y-4">
          {error && <p className="text-sm text-error">{error}</p>}
          <Input name="email" type="email" placeholder="邮箱" onChange={handleChange} required />
          <Input name="password" type="password" placeholder="密码" onChange={handleChange} required />
          <Input name="nickname" placeholder="昵称" onChange={handleChange} required />
          <select name="gender" onChange={handleChange}
            className="w-full h-12 px-4 rounded-md border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 outline-none">
            <option value={1}>男</option>
            <option value={0}>女</option>
          </select>
          <Input name="birth_date" type="date" placeholder="出生日期" onChange={handleChange} required />
          <Input name="city" placeholder="城市" onChange={handleChange} />
          <textarea name="bio" placeholder="个人介绍" onChange={handleChange}
            className="w-full px-4 py-3 rounded-md border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 outline-none h-20 resize-none" />
          <Input name="tags" placeholder="标签（用逗号分隔，如：旅行,美食,读书）" onChange={handleChange} />
          <Button type="submit" loading={loading} size="lg" className="w-full">
            {loading ? '注册中...' : '注册'}
          </Button>
          <p className="text-center text-sm text-gray-600 dark:text-gray-400">
            已有账号？ <Link to="/login" className="text-primary-500 hover:underline">立即登录</Link>
          </p>
        </form>
      </motion.div>
      <Toast
        message={toast.message}
        variant={toast.variant}
        isVisible={toast.visible}
        onClose={() => setToast({ ...toast, visible: false })}
      />
    </>
  );
}

// src/views/Register.vue
<template>
  <div class="min-h-screen flex items-center justify-center px-4 py-12 relative overflow-hidden">
    <!-- 飘浮装饰 -->
    <div class="floating-decorations absolute inset-0 pointer-events-none overflow-hidden">
      <div class="star" style="top: 10%; left: 10%; animation-delay: 0s;">✨</div>
      <div class="heart" style="top: 20%; right: 15%; animation-delay: 1s;">💕</div>
      <div class="star" style="top: 60%; left: 8%; animation-delay: 2s;">⭐</div>
      <div class="heart" style="top: 70%; right: 10%; animation-delay: 0.5s;">💖</div>
      <div class="star" style="top: 40%; right: 20%; animation-delay: 1.5s;">✨</div>
    </div>

    <!-- 背景装饰圆 -->
    <div class="absolute top-[-10%] left-[-10%] w-96 h-96 bg-pink-200/30 rounded-full blur-3xl pointer-events-none"></div>
    <div class="absolute bottom-[-10%] right-[-10%] w-96 h-96 bg-purple-200/30 rounded-full blur-3xl pointer-events-none"></div>

    <div class="card max-w-lg w-full relative z-10">
      <!-- 插画区域 -->
      <div class="illustration text-center -mt-20 mb-6">
        <div class="inline-block relative">
          <div class="w-32 h-32 mx-auto bg-gradient-to-br from-purple-300 via-pink-300 to-pink-400 rounded-full flex items-center justify-center shadow-uki-pink text-6xl relative z-10">
            🌸
          </div>
          <div class="absolute -top-2 -right-2 text-3xl animate-bounce-slow">✨</div>
          <div class="absolute -bottom-1 -left-3 text-2xl animate-bounce-slow" style="animation-delay: 0.5s;">💫</div>
        </div>
      </div>

      <div class="text-center mb-8">
        <h2 class="text-3xl font-bold text-gradient mb-2">加入我们</h2>
        <p class="text-uki-text-secondary text-sm">开启你的 UkiUki 之旅 🌷</p>
      </div>

      <form @submit.prevent="handleRegister" class="space-y-5">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-5">
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">邮箱</label>
            <input
              v-model="formData.email"
              type="email"
              placeholder="请输入邮箱"
              class="input"
              required
            />
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">昵称</label>
            <input
              v-model="formData.nickname"
              type="text"
              placeholder="请输入昵称"
              class="input"
              required
            />
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">密码</label>
            <input
              v-model="formData.password"
              type="password"
              placeholder="至少6位"
              class="input"
              required
              minlength="6"
            />
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">性别</label>
            <select v-model="formData.gender" class="input" required>
              <option value="">请选择</option>
              <option value="1">男 ♂️</option>
              <option value="2">女 ♀️</option>
            </select>
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">生日</label>
            <input
              v-model="formData.birth_date"
              type="date"
              class="input"
            />
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">标签</label>
            <input
              v-model="formData.tags"
              type="text"
              placeholder="旅行,美食,电影"
              class="input"
            />
          </div>
        </div>

        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">个人简介</label>
          <textarea
            v-model="formData.bio"
            class="input"
            rows="3"
            placeholder="介绍一下自己..."
          ></textarea>
        </div>

        <button type="submit" class="btn btn-primary w-full py-3.5" :disabled="loading">
          {{ loading ? '注册中...' : '立即注册 ✨' }}
        </button>

        <div v-if="error" class="text-red-500 text-center text-sm bg-red-50 rounded-xl py-2">
          {{ error }}
        </div>

        <div class="text-center text-gray-500 text-sm pt-2">
          已有账号？
          <RouterLink to="/login" class="text-pink-400 hover:text-pink-500 font-medium">立即登录 🌷</RouterLink>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { authAPI } from '@/api'
import { useUserStore } from '@/stores/user'

const router = useRouter()
const userStore = useUserStore()

const formData = ref({
  email: '',
  password: '',
  nickname: '',
  gender: '',
  birth_date: '',
  bio: '',
  tags: ''
})

const loading = ref(false)
const error = ref('')

const handleRegister = async () => {
  loading.value = true
  error.value = ''

  try {
    const response = await authAPI.register(formData.value)
    console.log('注册成功:', response)

    if (response.access_token) {
      userStore.setToken(response.access_token)
      userStore.setUser(response.user)
    }

    router.push('/matches')
  } catch (err) {
    console.error('注册失败:', err)
    error.value = err.response?.data?.detail || err.message || '注册失败，请重试'
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.floating-decorations .star,
.floating-decorations .heart {
  position: absolute;
  font-size: 20px;
  opacity: 0.6;
  animation: float 4s ease-in-out infinite;
}

@keyframes float {
  0%, 100% {
    transform: translateY(0) rotate(0deg);
    opacity: 0.4;
  }
  50% {
    transform: translateY(-20px) rotate(10deg);
    opacity: 0.8;
  }
}

@keyframes bounce-slow {
  0%, 100% { transform: translateY(0); }
  50% { transform: translateY(-6px); }
}
.animate-bounce-slow {
  animation: bounce-slow 2s ease-in-out infinite;
}
</style>
